config/routes.rb
Rails.application.routes.draw do
  get "new", to: 'games#new'
  post "score", to:'games#score'
  get "score", to: 'games#score'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/games_controller.rb
require 'open-uri'
require 'json'

class GamesController < ApplicationController

  def new
    @letters = ("a".."z").to_a.shuffle[0,11].join
  end

  def score
    @letters = params[:letters]
    if (params[:longest].length > @letters.length)
      @answer = "This is not a correct word"
      raise
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/new.html.erb
<h1>New Game</h1>
<h1> <%=@letters%> </h1>
<ul>
  <li> <%= @letters[0] %></li>
  <li> <%= @letters[1] %></li>
  <li> <%= @letters[2] %></li>
  <li> <%= @letters[3] %></li>
  <li> <%= @letters[4] %></li>
  <li> <%= @letters[5] %></li>
  <li> <%= @letters[6] %></li>
  <li> <%= @letters[7] %></li>
  <li> <%= @letters[8] %></li>
  <li> <%= @letters[9] %></li>
  <li> <%= @letters[10] %></li>
</ul>

<form action="/score">
  <input type="text" name="longest">
  <input type="submit" value="Type in a word">
  </form>

app/views/games/score.html.erb
<h1>Your result</h1>

<ul>
  <li>Attempt: <%= @attempt%></li>
  <li>Translation: <%= @result[:translation]%></li>
  <li>Time: <%= @result[:time]%></li>
  <li>Message: <%= @result[:message]%></li>
  <li>Score: <%= @result[:score]%></li>
</ul>

<%= link_to("Restart", game_path) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>